# Global Settings (Static)
system:
  random_seed: 42
  device: "cpu" # "cuda", "cpu", or "auto"
  save_dir: "./models"

data:
  path: "datasets/ml-latest-small/ratings.csv"
  val_split: 0.1
  test_split: 0.1

SimpleNCF:
  tuning:
    epochs: 3
    learning_rate: [1.0e-3, 5.0e-4, 1.0e-4]
    batch_size: [128, 256, 512]
    dropout: [0.0, 0.2, 0.5]
    layers:
      - [64, 32, 16] # Architecture A
      - [128, 64, 32] # Architecture B
    step_size: [3]
    gamma: [0.7]
    weight_decay: [1.0e-5]

  optim_params:
    epochs: 1
    learning_rate: 0.001
    batch_size: 4

    layers: 64

    # embedding dimensions
    emb_dim: 32

    # Scheduler
    step_size: 3
    gamma: 0.7

    # log
    log_every: 2000

DeepNCF:
  tuning:
    epochs: [1]
    learning_rate: [1.0e-3]
    batch_size: [128, 256]
    dropout: [0.2]
    layers:
      - [64, 32, 16] # Architecture A
      - [32, 16, 8] # Architecture B
    step_size: [3]
    gamma: [0.7]
    weight_decay: [1.0e-5]
    log_every: [20]
    emb_dim: [32]

  optim_params:
    epochs: 1
    learning_rate: 0.0005
    batch_size: 124

    dropout: 0.2
    layers: [64, 32, 16]

    # weight_decay: 1.0e-5

    # embedding dimensions
    emb_dim: 32

    # Scheduler
    step_size: 3
    gamma: 0.7

    # log
    log_every: 20
