# Global Settings (Static)
system:
  random_seed: 42
  device: "cpu" # "cuda", "cpu", or "auto"
  save_dir: "src/models"

data:
  location: "data/gold/ml-latest-small"

SimpleNCF:
  tuning:
    epochs: 3
    learning_rate: [1.0e-3, 5.0e-4, 1.0e-4]
    batch_size: [128, 256, 512]
    n_workers: [2]

    layers:
      - [64]
    dropout: [Null]

    # scheduler
    step_size: [3]
    gamma: [0.7]

    # embedding dimensions
    emb_dim: [32]

    # log / evaluation
    log_every: [20]
    threshold: [0.5]

  optim_params:
    epochs: 1
    learning_rate: 0.001
    batch_size: 4
    n_workers: 2

    layers: [64]
    dropout: Null

    # scheduler
    step_size: 3
    gamma: 0.7

    # embedding dimensions
    emb_dim: 32

    # log / evaluation
    log_every: 2000
    threshold: 0.5

DeepNCF:
  tuning:
    epochs: [20]
    learning_rate: [1.0e-3]
    batch_size: [128, 256]
    n_workers: [2]

    layers:
      - [64, 32, 16]
      - [32, 16, 8]
    dropout: [0.0, 0.2]

    # weight_decay: [1.0e-5]

    # scheduler
    step_size: [3]
    gamma: [0.7]
    # log / evaluation
    log_every: [60]
    threshold: [0.5]
    n_negatives: [4]

  optim_params:
    epochs: 1
    learning_rate: 0.0005
    batch_size: 128
    n_workers: 2

    layers: [64, 32, 16]
    dropout: 0.2

    # weight_decay: 1.0e-5

    # scheduler
    step_size: 3
    gamma: 0.7

    # log / evaluation
    log_every: 20
    threshold: 0.5
    n_negatives: 4
